comment_width = 60
condense_wildcard_suffixes = true
edition = "2018"
error_on_line_overflow = true
fn_args_density = "Tall"
force_multiline_blocks = true
format_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 79
merge_imports = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
