# schema https://starship.rs/config-schema.json
# docs https://starship.rs/config/
# system colors https://www.ditig.com/256-colors-cheat-sheet

[aws]
symbol = 'î­ '

[aws.region_aliases]
ap-southeast-1 = 'ğŸ‡¸ğŸ‡¬'
eu-west-1 = 'ğŸ‡®ğŸ‡ª'
eu-west-2 = 'ğŸ‡¬ğŸ‡§'
us-east-1 = 'ğŸ´ó µó ³ó ¶ó ¡ó ¿'
