# :schema https://github.com/jdx/mise/blob/main/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
awscli = "latest"
bat = "latest"
cargo-binstall = "latest"
delta = "latest"
fd = "latest"
go = "1.23.1"
java = "latest"
k9s = "0.26.7"
kubectl = "latest"
lazygit = "latest"
lua-language-server = "latest"
mdbook = "latest"
minikube = "latest"
node = "22.8.0"
perl = "5.40.0"
postgres = "13.0"
python = "3.13.3"
r = "4.4.1"
ripgrep = "latest"
httpie-go = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
ruff = "latest"
terraform = "latest"
terraform-ls = "latest"
tflint = "latest"
vault = "latest"
"aqua:Automattic/harper/harper-ls" = "latest"
"asdf:neovim" = "nightly"
"cargo:bottom" = "latest"
"cargo:cargo-deb" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-update" = "latest"
"cargo:diesel_cli" = "latest"
"cargo:oxker" = "latest"
"cargo:usage-cli" = "latest"
"go:github.com/sibprogrammer/xq" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:@shopify/cli" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:nginx-linter" = "latest"
"npm:nginxbeautifier" = "latest"
"npm:prettier" = "latest"
"npm:svelte-language-server" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:write-good" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:autotools-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:nginxfmt" = "latest"
"pipx:pgcli" = "latest"
"pipx:poethepoet" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:pre-commit" = "latest"
"pipx:pyright" = "latest"
"pipx:restview" = "latest"
"pipx:toml-sort" = "latest"
"pipx:ty" = "latest"
"pipx:visidata" = "latest"
"ubi:YS-L/csvlens" = "latest"
"ubi:artempyanykh/marksman" = "latest"
"ubi:chmln/sd" = "latest"
"ubi:nishanths/license" = "latest"
"ubi:supabase-community/postgres-language-server" = "latest"
