# :schema https://github.com/jdx/mise/blob/main/schema/mise.json

[settings]
idiomatic_version_file_enable_tools = ["rust"]
python.uv_venv_auto = true

[tools]
awscli = "latest"
bat = "latest"
biome = "latest"
bottom = "latest"
carapace = "latest"
cargo-binstall = "latest"
cargo-insta = "latest"
claude = "latest"
delta = "latest"
fd = "latest"
ghcup = "latest"
go = "1.23.1"
harper-ls = "latest"
hurl = "latest"
java = "25.0.1+8"
k9s = "0.26.7"
kubectl = "latest"
lazygit = "latest"
lua-language-server = "latest"
marksman = "latest"
mdbook = "latest"
minikube = "latest"
neovim = "nightly"
node = "24.11.1"
oxker = "latest"
perl = "5.40.0"
postgres = "13.0"
python = "3.14.2"
r = "4.4.1"
ripgrep = "latest"
ruff = "latest"
sd = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
tflint = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
"cargo:cargo-deb" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-update" = "latest"
"cargo:diesel_cli" = "latest"
"github:YS-L/csvlens" = "latest"
"github:github/github-mcp-server" = "latest"
"github:nishanths/license" = "latest"
"github:supabase-community/postgres-language-server" = "latest"
"go:github.com/sibprogrammer/xq" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:@shopify/cli" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:nginx-linter" = "latest"
"npm:nginxbeautifier" = "latest"
"npm:prettier" = "latest"
"npm:svelte-language-server" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:write-good" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:autotools-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:mdformat" = { version = "latest", uvx_args = "--with mdformat-footnote --with mdformat-front-matters --with mdformat-gfm --with mdformat-mkdocs --with mdformat-simple-breaks --with mdformat-wikilink" }
"pipx:nginxfmt" = "latest"
"pipx:pgcli" = "latest"
"pipx:poethepoet" = "latest"
"pipx:poetry" = { version = "latest", uvx_args = "--with poetry-plugin-export" }
"pipx:pre-commit" = "latest"
"pipx:pyright" = "latest"
"pipx:restview" = "latest"
"pipx:toml-sort" = "latest"
"pipx:ty" = "latest"
"pipx:visidata" = "latest"
